### ISSUE TITLE
clab_links: [] (showing empty)

### ISSUE THREAD

**Issue by chrisnand-github** [hellt/clab-config-demo#1]
Currently using containerlab version 0.55, clab_links variable not working as expected now. 

[root@localhost test]# clab config -t srlbgp.clab.yml template --vars
INFO[0000] Parsing & checking topology file: srlbgp.clab.yml
INFO[0000] srl1 vars = bgp:
  as: 65100
  groups:
    ebgp:
      peer_as: 65200
  neighbors:
    192.168.0.2:
      peer_group: ebgp
clab_kind: srl
clab_links: []
clab_management_ipv4: ""
clab_management_ipv6: ""
clab_node: srl1
clab_nodes: '{srl1: {...}, srl2: {...}, }'
clab_role: srl
clab_type: ixrd2
location: Brussels
system_ip: 10.0.0.1/32
INFO[0000] srl2 vars = bgp:
  as: 65200
  groups:
    ebgp:
      cluster_id: 1.2.3.4
      peer_as: 65100
  neighbors:
    192.168.0.1:
      peer_group: ebgp
clab_kind: srl
clab_links: []
clab_management_ipv4: ""
clab_management_ipv6: ""
clab_node: srl2
clab_nodes: '{srl1: {...}, srl2: {...}, }'
clab_role: srl
clab_type: ixrd2
location: Amsterdam
system_ip: 10.0.0.2/32

**Comment by hellt** [comment]
yes, the config engine is not supported in clab anymore
